title: David Black # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engineering Physics Student at the University of British Columbia
  <br><br>
  Engineering Portfolio 
  <br><br>
  <a href="https://www.linkedin.com/in/davidgblack/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="mailto:dgblack@ece.ubc.ca">Contact Me</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-157579510-1 # your Google Analytics tracking ID here
